version: "1.0"

services:
  frontend:
    build:
      context: ./front-habit-hub
      dockerfile: Dockerfile
    env_file:
      - ./front-habit-hub/.env
    ports:
      - "${FRONTEND_PORT}:4173"
    depends_on:
      - backend

  backend:
    build:
      context: ./back-habit-hub
      dockerfile: Dockerfile
    env_file:
      - ./back-habit-hub/.env_production
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
    - ./back-habit-hub/uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_LOCAL_PORT}:5432"
    volumes:
      - pgdata4:/var/lib/postgresql/data

volumes:
  pgdata4:
