export const HABIT_TAG = 'Habit'
export const HABIT_DETAILS_TAG = 'HabitDetails'
export const FRIENDSHIP_TAG = 'Friendship'
export const FRIENDSHIP_REQUEST_TAG = 'FriendshipRequest'
export const NOTIFICATION_TAG = 'Notification'
