export enum HabitCategory {
    HEALTH = 'HEALTH',
    FITNESS = 'FITNESS',
    LEARNING = 'LEARNING',
    MINDFULNESS = 'MINDFULNESS',
    PRODUCTIVITY = 'PRODUCTIVITY',
    NUTRITION = 'NUTRITION',
    SLEEP = 'SLEEP',
    FINANCE = 'FINANCE',
    SOCIAL = 'SOCIAL',
    SELF_CARE = 'SELF_CARE',
    HOBBY = 'HOBBY',
    WORK = 'WORK',
    CREATIVE = 'CREATIVE',
    SPIRITUALITY = 'SPIRITUALITY',
}

export const HabitCategoryIcons: Record<HabitCategory, string> = {
  [HabitCategory.HEALTH]: '🧬',
  [HabitCategory.FITNESS]: '💪',
  [HabitCategory.LEARNING]: '📚',
  [HabitCategory.MINDFULNESS]: '🧘‍♂️',
  [HabitCategory.PRODUCTIVITY]: '📈',
  [HabitCategory.NUTRITION]: '🥦',
  [HabitCategory.SLEEP]: '💤',
  [HabitCategory.FINANCE]: '🪙',
  [HabitCategory.SOCIAL]: '👨‍👩‍👧',
  [HabitCategory.SELF_CARE]: '🧖‍♀️',
  [HabitCategory.HOBBY]: '🎮',
  [HabitCategory.WORK]: '🖥️',
  [HabitCategory.CREATIVE]: '🧠',
  [HabitCategory.SPIRITUALITY]: '✨',
};
