name: Deploy Backend to EC2

on:
  push:
    branches:
      - master
    paths:
      - back-habit-hub/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/app/back-habit-hub
          git pull origin main
          npm install 
          pm2 restart habit-backend
